### ISSUE TITLE
Finden von Matches über die MatchID der PRM Seite mit der Api

### ISSUE THREAD

**Issue by Heuerus** [random-rip/primebot_backend#55]
Im Match Datenmodel befindet sich eine id und eine match_id. 
```
{
id*	                     [...]
match_id*	             [...]
prime_league_link*	     [...]
result	                     [...]
team*	        TeamForMatch {...}
enemy_team*	TeamForMatch {...}
}
```
- Bei der id handelt es sich vermutlich um die interne id der Datenbank. 
- Die match_id ist die selbe, die von der Prime League vergeben wird / in der PRM Url gefunden werden kann.

Problem: Es gibt aktuell noch keinen Weg über die match_id die Daten der "api/matches/" Route zukommen.

Auch in den Matchdaten (MatchForTeamDetails) über die "api/teams/" Route wird nur die match_id und nicht die tatsächliche Datenbank id zurückgegeben, sodass man nicht weiter nach den matchDetails
```
{
match_id*	              [...]
prime_league_link*            [...]
begin	                      [...]
result	                      [...]
match_day	              [...]
match_type	              {...}
nullable:                      true
updated_at*	              [...]
enemy_team*         EnemyTeam {...}
team_lineup*                  [...]
enemy_lineup*	              [...]
} 
```

**Comment by Grayknife** [comment]
Hi @Heuerus , du hast absolut recht.
Ich füge jetzt erstmal die ID zu `MatchForTeamDetails` hinzu.

Außerdem werde ich die API versionieren: `/api/v1/...` anstatt `/api/...`. Requests ohne Versionierung werden redirected auf den versionierten Endpunkt (v1). Die versionierten Endpunkte werden erstmal 1 zu 1 von den unversionierten Endpunkten (mit Ausnahme `/team/<id>/`, da wurde das  Feld `id` für die Matches hinzugefügt) übernommen.


Das grundlegende Problem

> Es gibt aktuell noch keinen Weg über die match_id die Daten der "api/matches/" Route zukommen.

ist leider nicht so trivial, weil wir die Matches potentiell "doppelt" speichern (wenn beide partizipierenden Teams des Matches den PrimeBot registrieren).
Aus dem Grund reicht die `match_id` nicht, um eindeutig ein Match aus der Datenbank zu holen, weil die Team Information fehlt.

Es gibt jetzt mehrere Möglichkeiten:
- Datenbankstruktur ändern, sodass die `match_id` eindeutig ist. -> Zu viel Aufwand, weil der ganze Bot/Notifiactions auf dieser Struktur gerade aufbaut
- `api/v1/teams/<team_id>/matches` und  `api/v1/teams/<team_id>/matches/<match_id>` implementieren (Nested Routings, die Team ID befindet sich im URI-path). Das wäre ein möglicher Ansatz.
- `api/v1/matches/by-id/<id>` für interne match ID und api/v1/matches/by-match-id/<match_id> für die externe MatchID
- `api/v1/matches/<match_id>/?team_id=<team_id>` implementieren (die TeamID **muss** als Queryparameter übergeben werden). Das wäre ein zweiter möglicher Ansatz. Das bedeutet aber auch, dass die Detailseite mit einer ID nicht mehr auffindbar sein wird. Wird die aber überhaupt noch benötigt, wenn man alles eindeutig mit der TeamID und MatchID retrieven kann?

**Comment by Heuerus** [comment]
Servus @Grayknife,

ich würde an dieser Stelle mit der Option 3 gehen. Einerseits stelle ich mir die Implementierung hier eher einfach vor, andererseits wird die Verwendung des Endpunkts als Konsument dadurch (Im Vergleich zu Option 2 und 4) vereinfacht, da man nur eine Variable benötigt. Des Weiteren wäre die match api dadurch etwas weniger verwirrend, wenn man direkt sieht welche id verwendet wird.

Im meinem Anwendungsfall würde ich z.B. gerne die Team Daten aus dem Match erfragen und nicht andersrum, da mein Skript die Daten verwendet um Matchgrafiken für Social Media zu erstellen. Da meine Org mittlerweile an die 35 Teams hat, betrifft das nicht alle Spiele von 1-2 Teams, sondern je 1-2 Spiele von 20 Teams. Daher wäre es deutlich einfacher sich nur auf die match_id zu beziehen, als noch eine Team_id mitgeben zu müssen. Wie bereits per DM erwähnt besteht das weitere Problem bei diesem Anwendungsfall aber darin, dass nicht unbedingt alle Teams den Bot verwenden und daher ggf. gar keine Match Daten vorhanden sind (Thema wird ja aber schon in den Issues #56 und #58 behandelt).

Ich hoffe ich konnte meine Sicht damit etwas erklären.

**Comment by Grayknife** [comment]
Bei Option 3 würde aber eine Liste an Matches zurückgegeben werden mit der Länge im Bereich [0,2], da es ja 2 Matches geben kann, die die gleiche MatchID haben. Dann müsstest du also noch herausfinden, welches jetzt das "richtige" für dich passende Match ist.
Ich denke es ist in jedem Fall eher sinnvoll den zweiten Parameter "TeamID" zusätzlich zu übergeben, da es sonst **nie** eindeutig ist.

**Comment by Grayknife** [comment]
Aufgrund der Abwärtskompatibilität ist weiterhin die Suche nach `api/v1/matches/<id/` erlaubt. Zusätzlich gibt es jetzt den Endpunkt:
`api/v1/matches/by-match-id/` der zwei queryparameter `team_id` und `match_id` entgegennimmt.

Hier die Open API reference: https://www.primebot.me/api/v1/#/v1/v1_matches_by_match_id_retrieve
